insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',1,1);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',1,2);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',1,3);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Edot-Mizrah',1,4);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Sphard',0,5);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',0,6);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',1,7);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',0,8);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',0,9);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Ashkenazi',1,10);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Sphard',0,11);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Edot-Mizrah',1,12);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',0,13);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Sphard',1,14);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Sphard',1,15);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',0,16);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Edot-Mizrah',1,17);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Sphard',1,18);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',1,19);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',0,20);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Sphard',1,21);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Ashkenazi',1,22);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',1,23);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',1,24);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Sphard',0,25);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',1,26);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Edot-Mizrah',0,27);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',0,28);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Ashkenazi',0,29);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Edot-Mizrah',0,30);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Edot-Mizrah',0,31);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',0,32);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',1,33);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',1,34);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Edot-Mizrah',0,35);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Edot-Mizrah',1,36);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Edot-Mizrah',1,37);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Edot-Mizrah',0,38);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Edot-Mizrah',1,39);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',1,40);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',1,41);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',0,42);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',0,43);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',1,44);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Ashkenazi',1,45);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',1,46);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',0,47);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',1,48);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',1,49);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,50);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',0,51);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Ashkenazi',0,52);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',1,53);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',1,54);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Edot-Mizrah',0,55);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Sphard',0,56);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',0,57);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Edot-Mizrah',0,58);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',1,59);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',1,60);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Ashkenazi',0,61);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Ashkenazi',1,62);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',0,63);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',1,64);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Sphard',1,65);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,66);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,67);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Ashkenazi',1,68);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',0,69);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Edot-Mizrah',0,70);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',0,71);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',0,72);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Ashkenazi',0,73);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Sphard',0,74);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',1,75);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',0,76);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',0,77);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',0,78);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',0,79);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Edot-Mizrah',1,80);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',0,81);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',0,82);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',1,83);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',1,84);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Sphard',1,85);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',1,86);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',1,87);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Sphard',0,88);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Sphard',1,89);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Ashkenazi',0,90);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',1,91);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Ashkenazi',0,92);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Edot-Mizrah',0,93);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Ashkenazi',1,94);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Edot-Mizrah',1,95);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,96);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',0,97);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',1,98);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',0,99);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',1,100);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Ashkenazi',1,101);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',1,102);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',0,103);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Ashkenazi',0,104);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',0,105);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',1,106);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',0,107);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Edot-Mizrah',1,108);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Ashkenazi',1,109);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Ashkenazi',0,110);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',1,111);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,112);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',0,113);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',1,114);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Ashkenazi',0,115);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',0,116);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',0,117);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',0,118);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',0,119);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',0,120);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Ashkenazi',1,121);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',1,122);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',0,123);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Sphard',1,124);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',0,125);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Edot-Mizrah',0,126);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Edot-Mizrah',0,127);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',0,128);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Sphard',1,129);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',1,130);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',0,131);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',1,132);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',1,133);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,134);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',1,135);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Edot-Mizrah',1,136);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',0,137);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Sphard',1,138);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Edot-Mizrah',0,139);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',1,140);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,141);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',0,142);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',0,143);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',1,144);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',1,145);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Ashkenazi',1,146);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',1,147);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,148);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',1,149);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',1,150);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',0,151);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Edot-Mizrah',0,152);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',1,153);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',0,154);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Ashkenazi',1,155);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Sphard',0,156);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Sphard',0,157);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',0,158);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Edot-Mizrah',1,159);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',1,160);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',1,161);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,162);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Edot-Mizrah',0,163);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Edot-Mizrah',1,164);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',1,165);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',0,166);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',1,167);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',0,168);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',1,169);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',1,170);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Edot-Mizrah',0,171);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Sphard',1,172);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Edot-Mizrah',0,173);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',0,174);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Ashkenazi',1,175);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',1,176);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',0,177);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',1,178);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',1,179);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Edot-Mizrah',1,180);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',1,181);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',0,182);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Edot-Mizrah',1,183);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',1,184);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',1,185);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Ashkenazi',0,186);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',0,187);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Ashkenazi',0,188);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Sphard',1,189);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Ashkenazi',0,190);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Ashkenazi',1,191);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Ashkenazi',0,192);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',1,193);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Sphard',0,194);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',0,195);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',1,196);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Ashkenazi',0,197);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',1,198);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Edot-Mizrah',1,199);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Ashkenazi',0,200);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',1,201);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',1,202);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',1,203);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Edot-Mizrah',0,204);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',1,205);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Edot-Mizrah',0,206);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',0,207);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',1,208);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',0,209);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Edot-Mizrah',0,210);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',1,211);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',0,212);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,213);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,214);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Edot-Mizrah',0,215);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',1,216);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',0,217);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',0,218);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Ashkenazi',1,219);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',1,220);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',0,221);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Sphard',1,222);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',1,223);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',1,224);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',1,225);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Ashkenazi',0,226);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',0,227);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Ashkenazi',0,228);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',1,229);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',0,230);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Edot-Mizrah',1,231);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Sphard',0,232);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',1,233);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',1,234);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Ashkenazi',1,235);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',1,236);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',0,237);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',0,238);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Sphard',0,239);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Edot-Mizrah',1,240);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Ashkenazi',1,241);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Ashkenazi',1,242);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',1,243);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',0,244);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',0,245);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',0,246);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Edot-Mizrah',1,247);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',1,248);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',1,249);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',0,250);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',1,251);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',0,252);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',0,253);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Edot-Mizrah',0,254);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',0,255);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Edot-Mizrah',1,256);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Sphard',1,257);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',0,258);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Sphard',1,259);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',1,260);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Edot-Mizrah',1,261);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',0,262);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',0,263);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',0,264);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Edot-Mizrah',0,265);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',0,266);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Edot-Mizrah',0,267);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',1,268);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',0,269);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',1,270);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',1,271);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',0,272);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',1,273);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',1,274);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',1,275);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Sphard',0,276);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',1,277);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',0,278);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',1,279);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',0,280);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',0,281);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Ashkenazi',0,282);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',1,283);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,284);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',0,285);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,286);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Edot-Mizrah',0,287);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',1,288);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,289);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',1,290);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',0,291);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',1,292);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',1,293);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Edot-Mizrah',0,294);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,295);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Edot-Mizrah',1,296);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Ashkenazi',1,297);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',1,298);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',1,299);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',1,300);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',0,301);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',0,302);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,303);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',1,304);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',1,305);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',0,306);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',0,307);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',1,308);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',1,309);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',1,310);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,311);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',0,312);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',0,313);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',1,314);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Ashkenazi',0,315);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Edot-Mizrah',0,316);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Sphard',1,317);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,318);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',1,319);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Edot-Mizrah',0,320);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Ashkenazi',0,321);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',1,322);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',1,323);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Edot-Mizrah',1,324);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,325);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',1,326);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',1,327);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',1,328);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Ashkenazi',1,329);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Edot-Mizrah',0,330);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',0,331);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',1,332);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Ashkenazi',0,333);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',0,334);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Sphard',0,335);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Edot-Mizrah',0,336);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',0,337);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',0,338);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',1,339);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Edot-Mizrah',1,340);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',1,341);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',1,342);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',1,343);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',1,344);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Sphard',0,345);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',0,346);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Edot-Mizrah',0,347);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,348);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Edot-Mizrah',0,349);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Hasidic','Ashkenazi',1,350);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Edot-Mizrah',0,351);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',1,352);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',0,353);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,354);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Ashkenazi',1,355);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Religious Zionism','Sphard',1,356);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',0,357);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',0,358);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',1,359);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Sphard',0,360);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',1,361);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Sphard',0,362);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Ashkenazi',0,363);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',0,364);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',1,365);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',1,366);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',1,367);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',0,368);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',0,369);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Ashkenazi',0,370);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',0,371);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',0,372);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Ashkenazi',0,373);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',0,374);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Sphard',1,375);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',0,376);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Sphard',0,377);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Ashkenazi',0,378);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Edot-Mizrah',1,379);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Hasidic','Sphard',0,380);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Sphard',1,381);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',1,382);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',0,383);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',1,384);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',0,385);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Sphard',0,386);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Haredi-Litai','Edot-Mizrah',1,387);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Ashkenazi',0,388);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Sphard',1,389);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Litai','Ashkenazi',1,390);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Religious Zionism','Ashkenazi',0,391);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Edot-Mizrah',0,392);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Litai','Edot-Mizrah',1,393);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Ashkenazi',0,394);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Religious Zionism','Sphard',0,395);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,1,'Haredi-Hasidic','Ashkenazi',1,396);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',0,397);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,1,'Haredi-Litai','Edot-Mizrah',0,398);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (1,0,'Haredi-Hasidic','Edot-Mizrah',0,399);
insert into military_rabbi (certified_Rabbi, Payytan, sector, ethnicity, preacher, id) values (0,0,'Religious Zionism','Edot-Mizrah',1,400);
