insert into commander (nickname, soliders_affection, security_clearance, id) values ('benchmark', 9, 4, 801);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('firmware', 6, 5, 802);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('4th generation', 10, 3, 803);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('knowledge user', 7, 4, 804);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('artificial intelligence', 1, 3, 805);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('user-facing', 5, 5, 806);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('User-friendly', 9, 5, 807);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('approach', 7, 2, 808);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('website', 8, 5, 809);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Front-line', 2, 3, 810);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('tangible', 7, 1, 811);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('pricing structure', 9, 3, 812);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('encoding', 6, 1, 813);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Up-sized', 4, 5, 814);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('radical', 7, 2, 815);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('algorithm', 1, 5, 816);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('zero administration', 6, 1, 817);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('website', 2, 4, 818);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('encompassing', 4, 3, 819);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('system engine', 9, 4, 820);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('multimedia', 6, 1, 821);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('collaboration', 10, 3, 822);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Future-proofed', 5, 1, 823);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('discrete', 1, 3, 824);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('alliance', 8, 1, 825);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Integrated', 7, 1, 826);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('encoding', 10, 2, 827);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('customer loyalty', 10, 4, 828);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('4th generation', 3, 2, 829);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('capability', 2, 1, 830);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('system-worthy', 5, 3, 831);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Fully-configurable', 1, 5, 832);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Streamlined', 4, 1, 833);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('discrete', 7, 4, 834);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Vision-oriented', 5, 1, 835);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('website', 5, 5, 836);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('modular', 2, 2, 837);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('productivity', 2, 4, 838);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('demand-driven', 1, 1, 839);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('superstructure', 6, 2, 840);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('task-force', 5, 5, 841);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Enhanced', 6, 3, 842);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Re-engineered', 8, 2, 843);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('challenge', 10, 5, 844);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('hybrid', 5, 3, 845);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('paradigm', 8, 3, 846);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('portal', 6, 5, 847);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Profit-focused', 9, 3, 848);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('uniform', 1, 3, 849);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('client-server', 9, 3, 850);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Devolved', 3, 1, 851);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('website', 2, 2, 852);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('hardware', 4, 1, 853);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('encompassing', 6, 3, 854);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('bottom-line', 9, 3, 855);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('homogeneous', 7, 1, 856);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('adapter', 6, 1, 857);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Versatile', 2, 4, 858);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Multi-tiered', 1, 3, 859);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('bandwidth-monitored', 6, 3, 860);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('client-server', 9, 4, 861);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('zero tolerance', 9, 1, 862);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('maximized', 2, 3, 863);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Polarised', 3, 3, 864);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('algorithm', 4, 1, 865);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('leverage', 9, 4, 866);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('zero tolerance', 5, 4, 867);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('frame', 7, 5, 868);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Graphic Interface', 7, 2, 869);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('initiative', 10, 2, 870);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('alliance', 8, 2, 871);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('24 hour', 2, 5, 872);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('internet solution', 6, 1, 873);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('strategy', 8, 4, 874);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Up-sized', 2, 3, 875);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Enterprise-wide', 5, 4, 876);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('local area network', 3, 5, 877);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Ameliorated', 6, 5, 878);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('attitude-oriented', 6, 1, 879);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Extended', 10, 1, 880);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Quality-focused', 2, 4, 881);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('asynchronous', 2, 3, 882);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('demand-driven', 8, 5, 883);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('cohesive', 6, 4, 884);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('local area network', 1, 5, 885);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Adaptive', 9, 4, 886);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('hardware', 2, 4, 887);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('radical', 3, 5, 888);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('intermediate', 5, 3, 889);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Proactive', 3, 3, 890);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Reduced', 6, 4, 891);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('demand-driven', 10, 2, 892);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('intranet', 4, 2, 893);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('executive', 4, 1, 894);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Fundamental', 1, 3, 895);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('hierarchy', 3, 2, 896);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Ergonomic', 8, 4, 897);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('intranet', 2, 3, 898);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('capability', 4, 5, 899);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('needs-based', 8, 5, 900);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Advanced', 7, 4, 901);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('toolset', 5, 1, 902);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('upward-trending', 7, 3, 903);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Programmable', 5, 5, 904);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Optimized', 10, 2, 905);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('knowledge base', 6, 1, 906);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('transitional', 2, 3, 907);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Expanded', 10, 2, 908);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('instruction set', 2, 4, 909);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('intangible', 4, 2, 910);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Multi-lateral', 9, 1, 911);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('didactic', 3, 1, 912);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Enterprise-wide', 5, 4, 913);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Innovative', 1, 3, 914);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('neutral', 10, 4, 915);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Graphical User Interface', 10, 5, 916);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('synergy', 2, 2, 917);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('support', 6, 2, 918);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('multimedia', 9, 2, 919);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('neutral', 9, 3, 920);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('systemic', 6, 1, 921);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('bi-directional', 6, 3, 922);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('matrices', 3, 4, 923);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Vision-oriented', 5, 3, 924);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Up-sized', 10, 4, 925);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('groupware', 3, 5, 926);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('service-desk', 10, 4, 927);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('encompassing', 7, 5, 928);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('exuding', 1, 5, 929);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Persevering', 10, 2, 930);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('User-centric', 10, 3, 931);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('hub', 10, 3, 932);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('cohesive', 2, 2, 933);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('encoding', 2, 4, 934);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('user-facing', 4, 4, 935);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('task-force', 2, 2, 936);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('orchestration', 1, 4, 937);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('neural-net', 10, 1, 938);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Persistent', 4, 4, 939);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Stand-alone', 7, 4, 940);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Balanced', 7, 1, 941);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Exclusive', 3, 3, 942);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('system engine', 2, 4, 943);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('homogeneous', 1, 5, 944);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('definition', 7, 3, 945);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Fundamental', 3, 4, 946);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('grid-enabled', 6, 5, 947);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('throughput', 3, 2, 948);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('encryption', 5, 3, 949);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('flexibility', 10, 5, 950);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('high-level', 4, 5, 951);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('next generation', 1, 3, 952);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Multi-layered', 3, 5, 953);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('policy', 5, 5, 954);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Pre-emptive', 9, 2, 955);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('utilisation', 5, 4, 956);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('concept', 9, 1, 957);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('attitude-oriented', 6, 3, 958);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('upward-trending', 9, 2, 959);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('customer loyalty', 6, 1, 960);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Implemented', 8, 3, 961);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('hardware', 8, 3, 962);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Versatile', 10, 5, 963);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('tertiary', 3, 4, 964);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('challenge', 8, 3, 965);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Virtual', 2, 2, 966);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('cohesive', 7, 2, 967);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('regional', 1, 1, 968);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('paradigm', 8, 5, 969);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Quality-focused', 4, 3, 970);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('implementation', 10, 5, 971);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Quality-focused', 4, 4, 972);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('actuating', 8, 4, 973);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('regional', 1, 2, 974);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('flexibility', 8, 3, 975);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Synergistic', 8, 4, 976);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('challenge', 8, 2, 977);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Team-oriented', 1, 3, 978);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('object-oriented', 1, 3, 979);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Advanced', 2, 5, 980);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('actuating', 6, 4, 981);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('superstructure', 7, 5, 982);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Streamlined', 1, 4, 983);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('zero administration', 7, 2, 984);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Switchable', 9, 2, 985);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Switchable', 7, 2, 986);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('leading edge', 5, 5, 987);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('solution', 10, 2, 988);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('circuit', 6, 4, 989);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('bottom-line', 4, 5, 990);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('content-based', 1, 1, 991);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('well-modulated', 3, 5, 992);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('groupware', 9, 1, 993);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('intangible', 10, 3, 994);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('neural-net', 6, 5, 995);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('neural-net', 10, 3, 996);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Programmable', 5, 1, 997);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('matrix', 10, 1, 998);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('grid-enabled', 6, 2, 999);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Graphical User Interface', 9, 4, 1000);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('solution-oriented', 6, 3, 1001);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Future-proofed', 5, 5, 1002);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('object-oriented', 9, 4, 1003);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('success', 8, 1, 1004);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('matrix', 7, 3, 1005);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Operative', 7, 3, 1006);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('didactic', 3, 2, 1007);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Operative', 5, 5, 1008);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Front-line', 5, 2, 1009);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('structure', 9, 3, 1010);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Synchronised', 6, 3, 1011);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('contingency', 6, 3, 1012);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Pre-emptive', 3, 1, 1013);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('clear-thinking', 6, 4, 1014);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Profit-focused', 9, 2, 1015);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('object-oriented', 2, 3, 1016);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('synergy', 9, 5, 1017);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('toolset', 5, 5, 1018);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('tangible', 5, 3, 1019);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('multi-state', 4, 3, 1020);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('project', 5, 5, 1021);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('even-keeled', 7, 1, 1022);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('encryption', 6, 5, 1023);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('software', 5, 4, 1024);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('adapter', 4, 3, 1025);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('help-desk', 2, 3, 1026);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Synergized', 8, 1, 1027);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('hierarchy', 9, 3, 1028);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('secondary', 7, 2, 1029);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('hub', 2, 2, 1030);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('intermediate', 8, 1, 1031);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Reduced', 8, 1, 1032);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('function', 3, 4, 1033);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('4th generation', 7, 3, 1034);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('exuding', 6, 2, 1035);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Open-source', 1, 2, 1036);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Team-oriented', 3, 4, 1037);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('architecture', 3, 1, 1038);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('functionalities', 1, 1, 1039);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('intermediate', 1, 3, 1040);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('customer loyalty', 10, 3, 1041);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Optimized', 9, 1, 1042);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Adaptive', 5, 3, 1043);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('secondary', 9, 4, 1044);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('modular', 2, 5, 1045);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('groupware', 3, 1, 1046);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('impactful', 9, 5, 1047);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('frame', 2, 3, 1048);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Synchronised', 2, 4, 1049);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Grass-roots', 1, 2, 1050);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('help-desk', 2, 4, 1051);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('solution', 2, 4, 1052);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Seamless', 3, 4, 1053);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('homogeneous', 10, 3, 1054);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('intangible', 4, 3, 1055);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('hierarchy', 8, 3, 1056);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('intermediate', 4, 4, 1057);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Team-oriented', 1, 5, 1058);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('client-driven', 1, 2, 1059);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('5th generation', 6, 3, 1060);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('multi-state', 3, 5, 1061);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('transitional', 5, 3, 1062);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('value-added', 7, 2, 1063);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('homogeneous', 10, 3, 1064);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('system engine', 10, 4, 1065);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Re-contextualized', 8, 3, 1066);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('superstructure', 3, 4, 1067);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Cloned', 4, 1, 1068);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Upgradable', 8, 5, 1069);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('algorithm', 4, 1, 1070);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('contingency', 3, 5, 1071);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('executive', 2, 5, 1072);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('middleware', 2, 2, 1073);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Sharable', 9, 1, 1074);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('eco-centric', 5, 3, 1075);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('website', 2, 5, 1076);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('well-modulated', 5, 2, 1077);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('full-range', 5, 1, 1078);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Vision-oriented', 5, 2, 1079);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('paradigm', 3, 4, 1080);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('interface', 6, 1, 1081);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('user-facing', 10, 2, 1082);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('software', 4, 3, 1083);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('methodology', 2, 4, 1084);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('multi-tasking', 5, 3, 1085);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Quality-focused', 2, 1, 1086);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Re-contextualized', 1, 1, 1087);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Horizontal', 5, 4, 1088);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('well-modulated', 7, 1, 1089);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('array', 2, 5, 1090);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('firmware', 9, 1, 1091);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('success', 9, 1, 1092);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('homogeneous', 9, 2, 1093);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('budgetary management', 4, 4, 1094);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('24/7', 5, 5, 1095);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('global', 8, 1, 1096);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('transitional', 8, 5, 1097);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('pricing structure', 2, 2, 1098);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('multi-tasking', 3, 5, 1099);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('foreground', 10, 3, 1100);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('circuit', 3, 1, 1101);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('matrices', 7, 1, 1102);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('tangible', 10, 5, 1103);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Up-sized', 9, 5, 1104);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Total', 8, 3, 1105);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('approach', 8, 2, 1106);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('object-oriented', 1, 2, 1107);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('firmware', 8, 2, 1108);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('encoding', 7, 5, 1109);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Cross-platform', 6, 1, 1110);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('hybrid', 7, 5, 1111);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Implemented', 4, 4, 1112);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('installation', 9, 3, 1113);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('protocol', 10, 1, 1114);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Synergized', 7, 2, 1115);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Secured', 3, 1, 1116);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('empowering', 5, 1, 1117);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('analyzer', 6, 2, 1118);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('workforce', 4, 3, 1119);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Phased', 9, 3, 1120);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Fundamental', 4, 5, 1121);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('bi-directional', 6, 5, 1122);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('open system', 5, 2, 1123);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('encoding', 1, 5, 1124);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Advanced', 8, 1, 1125);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('local', 2, 1, 1126);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('executive', 9, 2, 1127);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('actuating', 3, 4, 1128);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Ergonomic', 1, 3, 1129);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('pricing structure', 5, 3, 1130);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Monitored', 10, 4, 1131);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('application', 9, 4, 1132);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Future-proofed', 7, 3, 1133);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Optional', 4, 4, 1134);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Self-enabling', 1, 3, 1135);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Persevering', 6, 4, 1136);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('didactic', 6, 4, 1137);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('dedicated', 5, 4, 1138);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('knowledge user', 3, 4, 1139);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('migration', 10, 3, 1140);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('intangible', 8, 2, 1141);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('background', 5, 5, 1142);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('local', 4, 1, 1143);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Persistent', 9, 5, 1144);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Pre-emptive', 3, 3, 1145);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Synergized', 10, 2, 1146);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('solution', 9, 5, 1147);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('value-added', 7, 5, 1148);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Business-focused', 6, 3, 1149);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('open architecture', 8, 5, 1150);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('challenge', 8, 2, 1151);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('zero tolerance', 1, 4, 1152);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('structure', 1, 2, 1153);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('website', 9, 5, 1154);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('composite', 10, 1, 1155);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('tangible', 5, 1, 1156);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Public-key', 2, 3, 1157);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Secured', 4, 3, 1158);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Object-based', 3, 5, 1159);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('customer loyalty', 6, 2, 1160);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('modular', 8, 5, 1161);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('didactic', 2, 1, 1162);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('array', 7, 5, 1163);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('background', 10, 5, 1164);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('toolset', 9, 1, 1165);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Organized', 4, 1, 1166);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('concept', 2, 3, 1167);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('fresh-thinking', 6, 4, 1168);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Graphical User Interface', 9, 5, 1169);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Open-source', 6, 2, 1170);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('eco-centric', 3, 5, 1171);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('info-mediaries', 7, 1, 1172);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('internet solution', 10, 1, 1173);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Universal', 3, 1, 1174);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Monitored', 6, 5, 1175);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('24/7', 9, 3, 1176);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('logistical', 1, 3, 1177);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('software', 9, 4, 1178);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('bifurcated', 8, 3, 1179);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Multi-layered', 8, 3, 1180);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('contingency', 7, 1, 1181);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('support', 10, 2, 1182);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Synergistic', 8, 3, 1183);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Synergistic', 9, 2, 1184);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Streamlined', 4, 5, 1185);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('productivity', 3, 4, 1186);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('policy', 9, 1, 1187);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('projection', 3, 1, 1188);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('process improvement', 3, 2, 1189);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('application', 6, 5, 1190);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Decentralized', 4, 4, 1191);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Persistent', 10, 1, 1192);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('grid-enabled', 4, 4, 1193);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('system engine', 6, 1, 1194);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Exclusive', 1, 3, 1195);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Advanced', 8, 1, 1196);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('Expanded', 8, 2, 1197);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('time-frame', 4, 4, 1198);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('dedicated', 2, 5, 1199);
insert into commander (nickname, soliders_affection, security_clearance, id) values ('non-volatile', 8, 2, 1200);
