insert into solider_in (responsibility, team_number, id) values ('communications specialist', 1, 730);
insert into solider_in (responsibility, team_number, id) values ('engineer', 2, 403);
insert into solider_in (responsibility, team_number, id) values ('marksman', 3, 495);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 4, 818);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 5, 1025);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 6, 604);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 7, 327);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 8, 385);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 9, 917);
insert into solider_in (responsibility, team_number, id) values ('engineer', 10, 726);
insert into solider_in (responsibility, team_number, id) values ('sniper', 11, 924);
insert into solider_in (responsibility, team_number, id) values ('scout', 12, 324);
insert into solider_in (responsibility, team_number, id) values ('marksman', 13, 570);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 14, 446);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 15, 681);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 16, 1057);
insert into solider_in (responsibility, team_number, id) values ('engineer', 17, 945);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 18, 926);
insert into solider_in (responsibility, team_number, id) values ('engineer', 19, 146);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 20, 708);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 21, 1064);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 22, 977);
insert into solider_in (responsibility, team_number, id) values ('scout', 23, 699);
insert into solider_in (responsibility, team_number, id) values ('scout', 24, 183);
insert into solider_in (responsibility, team_number, id) values ('sniper', 25, 879);
insert into solider_in (responsibility, team_number, id) values ('sniper', 26, 751);
insert into solider_in (responsibility, team_number, id) values ('sniper', 27, 963);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 28, 13);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 29, 186);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 30, 917);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 31, 990);
insert into solider_in (responsibility, team_number, id) values ('sniper', 32, 336);
insert into solider_in (responsibility, team_number, id) values ('scout', 33, 559);
insert into solider_in (responsibility, team_number, id) values ('sniper', 34, 84);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 35, 689);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 36, 771);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 37, 132);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 38, 1026);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 39, 988);
insert into solider_in (responsibility, team_number, id) values ('engineer', 40, 598);
insert into solider_in (responsibility, team_number, id) values ('sniper', 41, 806);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 42, 644);
insert into solider_in (responsibility, team_number, id) values ('engineer', 43, 48);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 44, 1132);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 45, 187);
insert into solider_in (responsibility, team_number, id) values ('scout', 46, 1084);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 47, 1092);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 48, 581);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 49, 170);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 50, 418);
insert into solider_in (responsibility, team_number, id) values ('engineer', 51, 803);
insert into solider_in (responsibility, team_number, id) values ('marksman', 52, 281);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 53, 514);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 54, 736);
insert into solider_in (responsibility, team_number, id) values ('marksman', 55, 963);
insert into solider_in (responsibility, team_number, id) values ('scout', 56, 948);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 57, 1083);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 58, 69);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 59, 748);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 60, 434);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 61, 1176);
insert into solider_in (responsibility, team_number, id) values ('marksman', 62, 507);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 63, 197);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 64, 1041);
insert into solider_in (responsibility, team_number, id) values ('scout', 65, 146);
insert into solider_in (responsibility, team_number, id) values ('sniper', 66, 551);
insert into solider_in (responsibility, team_number, id) values ('sniper', 67, 892);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 68, 440);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 69, 275);
insert into solider_in (responsibility, team_number, id) values ('sniper', 70, 1057);
insert into solider_in (responsibility, team_number, id) values ('sniper', 71, 631);
insert into solider_in (responsibility, team_number, id) values ('scout', 72, 384);
insert into solider_in (responsibility, team_number, id) values ('scout', 73, 625);
insert into solider_in (responsibility, team_number, id) values ('marksman', 74, 1060);
insert into solider_in (responsibility, team_number, id) values ('engineer', 75, 262);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 76, 251);
insert into solider_in (responsibility, team_number, id) values ('marksman', 77, 77);
insert into solider_in (responsibility, team_number, id) values ('engineer', 78, 36);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 79, 1141);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 80, 610);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 81, 1151);
insert into solider_in (responsibility, team_number, id) values ('marksman', 82, 426);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 83, 580);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 84, 845);
insert into solider_in (responsibility, team_number, id) values ('scout', 85, 818);
insert into solider_in (responsibility, team_number, id) values ('scout', 86, 193);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 87, 153);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 88, 460);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 89, 585);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 90, 729);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 91, 534);
insert into solider_in (responsibility, team_number, id) values ('marksman', 92, 615);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 93, 941);
insert into solider_in (responsibility, team_number, id) values ('engineer', 94, 67);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 95, 636);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 96, 144);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 97, 221);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 98, 259);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 99, 320);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 100, 1022);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 101, 491);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 102, 182);
insert into solider_in (responsibility, team_number, id) values ('sniper', 103, 489);
insert into solider_in (responsibility, team_number, id) values ('marksman', 104, 636);
insert into solider_in (responsibility, team_number, id) values ('sniper', 105, 612);
insert into solider_in (responsibility, team_number, id) values ('marksman', 106, 946);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 107, 37);
insert into solider_in (responsibility, team_number, id) values ('marksman', 108, 59);
insert into solider_in (responsibility, team_number, id) values ('engineer', 109, 177);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 110, 199);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 111, 883);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 112, 904);
insert into solider_in (responsibility, team_number, id) values ('scout', 113, 647);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 114, 754);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 115, 797);
insert into solider_in (responsibility, team_number, id) values ('sniper', 116, 436);
insert into solider_in (responsibility, team_number, id) values ('engineer', 117, 662);
insert into solider_in (responsibility, team_number, id) values ('scout', 118, 1068);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 119, 565);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 120, 771);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 121, 188);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 122, 159);
insert into solider_in (responsibility, team_number, id) values ('engineer', 123, 914);
insert into solider_in (responsibility, team_number, id) values ('scout', 124, 390);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 125, 160);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 126, 626);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 127, 544);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 128, 675);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 129, 687);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 130, 656);
insert into solider_in (responsibility, team_number, id) values ('scout', 131, 750);
insert into solider_in (responsibility, team_number, id) values ('engineer', 132, 583);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 133, 121);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 134, 680);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 135, 739);
insert into solider_in (responsibility, team_number, id) values ('scout', 136, 989);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 137, 180);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 138, 463);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 139, 394);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 140, 126);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 141, 792);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 142, 1099);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 143, 260);
insert into solider_in (responsibility, team_number, id) values ('scout', 144, 795);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 145, 272);
insert into solider_in (responsibility, team_number, id) values ('engineer', 146, 406);
insert into solider_in (responsibility, team_number, id) values ('engineer', 147, 893);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 148, 643);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 149, 871);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 150, 1189);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 151, 1137);
insert into solider_in (responsibility, team_number, id) values ('sniper', 152, 568);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 153, 189);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 154, 396);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 155, 62);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 156, 978);
insert into solider_in (responsibility, team_number, id) values ('scout', 157, 598);
insert into solider_in (responsibility, team_number, id) values ('engineer', 158, 116);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 159, 329);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 160, 651);
insert into solider_in (responsibility, team_number, id) values ('sniper', 161, 229);
insert into solider_in (responsibility, team_number, id) values ('scout', 162, 858);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 163, 510);
insert into solider_in (responsibility, team_number, id) values ('scout', 164, 983);
insert into solider_in (responsibility, team_number, id) values ('scout', 165, 844);
insert into solider_in (responsibility, team_number, id) values ('marksman', 166, 537);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 167, 761);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 168, 1180);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 169, 966);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 170, 760);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 171, 999);
insert into solider_in (responsibility, team_number, id) values ('engineer', 172, 961);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 173, 1158);
insert into solider_in (responsibility, team_number, id) values ('sniper', 174, 387);
insert into solider_in (responsibility, team_number, id) values ('engineer', 175, 651);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 176, 485);
insert into solider_in (responsibility, team_number, id) values ('sniper', 177, 267);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 178, 74);
insert into solider_in (responsibility, team_number, id) values ('sniper', 179, 268);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 180, 1057);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 181, 1001);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 182, 700);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 183, 639);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 184, 268);
insert into solider_in (responsibility, team_number, id) values ('scout', 185, 648);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 186, 962);
insert into solider_in (responsibility, team_number, id) values ('marksman', 187, 210);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 188, 219);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 189, 39);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 190, 596);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 191, 982);
insert into solider_in (responsibility, team_number, id) values ('engineer', 192, 180);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 193, 704);
insert into solider_in (responsibility, team_number, id) values ('marksman', 194, 284);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 195, 224);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 196, 245);
insert into solider_in (responsibility, team_number, id) values ('scout', 197, 1111);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 198, 608);
insert into solider_in (responsibility, team_number, id) values ('engineer', 199, 604);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 200, 1177);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 201, 1054);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 202, 1084);
insert into solider_in (responsibility, team_number, id) values ('engineer', 203, 455);
insert into solider_in (responsibility, team_number, id) values ('marksman', 204, 1077);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 205, 395);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 206, 220);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 207, 934);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 208, 740);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 209, 550);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 210, 483);
insert into solider_in (responsibility, team_number, id) values ('scout', 211, 911);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 212, 597);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 213, 1000);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 214, 1003);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 215, 58);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 216, 929);
insert into solider_in (responsibility, team_number, id) values ('marksman', 217, 289);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 218, 978);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 219, 170);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 220, 5);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 221, 894);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 222, 676);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 223, 43);
insert into solider_in (responsibility, team_number, id) values ('engineer', 224, 203);
insert into solider_in (responsibility, team_number, id) values ('scout', 225, 582);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 226, 209);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 227, 428);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 228, 853);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 229, 5);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 230, 561);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 231, 789);
insert into solider_in (responsibility, team_number, id) values ('engineer', 232, 155);
insert into solider_in (responsibility, team_number, id) values ('engineer', 233, 595);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 234, 182);
insert into solider_in (responsibility, team_number, id) values ('sniper', 235, 826);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 236, 88);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 237, 320);
insert into solider_in (responsibility, team_number, id) values ('scout', 238, 884);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 239, 752);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 240, 952);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 241, 1151);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 242, 137);
insert into solider_in (responsibility, team_number, id) values ('scout', 243, 466);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 244, 728);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 245, 1055);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 246, 437);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 247, 506);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 248, 685);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 249, 1010);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 250, 264);
insert into solider_in (responsibility, team_number, id) values ('sniper', 251, 625);
insert into solider_in (responsibility, team_number, id) values ('marksman', 252, 1155);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 253, 277);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 254, 842);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 255, 728);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 256, 629);
insert into solider_in (responsibility, team_number, id) values ('sniper', 257, 868);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 258, 6);
insert into solider_in (responsibility, team_number, id) values ('sniper', 259, 494);
insert into solider_in (responsibility, team_number, id) values ('marksman', 260, 1121);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 261, 434);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 262, 844);
insert into solider_in (responsibility, team_number, id) values ('engineer', 263, 48);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 264, 728);
insert into solider_in (responsibility, team_number, id) values ('engineer', 265, 561);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 266, 573);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 267, 16);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 268, 131);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 269, 292);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 270, 418);
insert into solider_in (responsibility, team_number, id) values ('sniper', 271, 568);
insert into solider_in (responsibility, team_number, id) values ('marksman', 272, 927);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 273, 451);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 274, 337);
insert into solider_in (responsibility, team_number, id) values ('marksman', 275, 875);
insert into solider_in (responsibility, team_number, id) values ('scout', 276, 454);
insert into solider_in (responsibility, team_number, id) values ('marksman', 277, 1133);
insert into solider_in (responsibility, team_number, id) values ('sniper', 278, 76);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 279, 1193);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 280, 106);
insert into solider_in (responsibility, team_number, id) values ('engineer', 281, 867);
insert into solider_in (responsibility, team_number, id) values ('scout', 282, 237);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 283, 817);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 284, 683);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 285, 922);
insert into solider_in (responsibility, team_number, id) values ('sniper', 286, 875);
insert into solider_in (responsibility, team_number, id) values ('engineer', 287, 1056);
insert into solider_in (responsibility, team_number, id) values ('sniper', 288, 880);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 289, 235);
insert into solider_in (responsibility, team_number, id) values ('engineer', 290, 128);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 291, 999);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 292, 1130);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 293, 440);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 294, 1083);
insert into solider_in (responsibility, team_number, id) values ('marksman', 295, 565);
insert into solider_in (responsibility, team_number, id) values ('scout', 296, 384);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 297, 96);
insert into solider_in (responsibility, team_number, id) values ('engineer', 298, 1180);
insert into solider_in (responsibility, team_number, id) values ('sniper', 299, 1157);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 300, 343);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 301, 723);
insert into solider_in (responsibility, team_number, id) values ('sniper', 302, 507);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 303, 891);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 304, 955);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 305, 43);
insert into solider_in (responsibility, team_number, id) values ('marksman', 306, 1069);
insert into solider_in (responsibility, team_number, id) values ('engineer', 307, 415);
insert into solider_in (responsibility, team_number, id) values ('scout', 308, 810);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 309, 303);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 310, 89);
insert into solider_in (responsibility, team_number, id) values ('marksman', 311, 1004);
insert into solider_in (responsibility, team_number, id) values ('marksman', 312, 798);
insert into solider_in (responsibility, team_number, id) values ('marksman', 313, 1146);
insert into solider_in (responsibility, team_number, id) values ('engineer', 314, 304);
insert into solider_in (responsibility, team_number, id) values ('scout', 315, 701);
insert into solider_in (responsibility, team_number, id) values ('scout', 316, 1011);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 317, 1035);
insert into solider_in (responsibility, team_number, id) values ('engineer', 318, 929);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 319, 264);
insert into solider_in (responsibility, team_number, id) values ('engineer', 320, 244);
insert into solider_in (responsibility, team_number, id) values ('marksman', 321, 1089);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 322, 1040);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 323, 6);
insert into solider_in (responsibility, team_number, id) values ('marksman', 324, 581);
insert into solider_in (responsibility, team_number, id) values ('sniper', 325, 1147);
insert into solider_in (responsibility, team_number, id) values ('sniper', 326, 305);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 327, 313);
insert into solider_in (responsibility, team_number, id) values ('sniper', 328, 334);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 329, 1192);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 330, 115);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 331, 513);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 332, 1070);
insert into solider_in (responsibility, team_number, id) values ('marksman', 333, 876);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 334, 376);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 335, 461);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 336, 346);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 337, 1183);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 338, 652);
insert into solider_in (responsibility, team_number, id) values ('engineer', 339, 897);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 340, 311);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 341, 326);
insert into solider_in (responsibility, team_number, id) values ('sniper', 342, 551);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 343, 566);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 344, 939);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 345, 684);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 346, 365);
insert into solider_in (responsibility, team_number, id) values ('engineer', 347, 442);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 348, 675);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 349, 1092);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 350, 196);
insert into solider_in (responsibility, team_number, id) values ('engineer', 351, 838);
insert into solider_in (responsibility, team_number, id) values ('sniper', 352, 1048);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 353, 724);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 354, 902);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 355, 217);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 356, 425);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 357, 498);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 358, 1139);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 359, 552);
insert into solider_in (responsibility, team_number, id) values ('marksman', 360, 931);
insert into solider_in (responsibility, team_number, id) values ('scout', 361, 923);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 362, 1009);
insert into solider_in (responsibility, team_number, id) values ('sniper', 363, 1072);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 364, 1064);
insert into solider_in (responsibility, team_number, id) values ('engineer', 365, 285);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 366, 65);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 367, 1182);
insert into solider_in (responsibility, team_number, id) values ('scout', 368, 1018);
insert into solider_in (responsibility, team_number, id) values ('sniper', 369, 651);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 370, 547);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 371, 382);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 372, 585);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 373, 709);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 374, 368);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 375, 612);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 376, 930);
insert into solider_in (responsibility, team_number, id) values ('sniper', 377, 365);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 378, 340);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 379, 152);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 380, 1186);
insert into solider_in (responsibility, team_number, id) values ('sniper', 381, 332);
insert into solider_in (responsibility, team_number, id) values ('demolition expert', 382, 394);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 383, 949);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 384, 646);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 385, 585);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 386, 1103);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 387, 1101);
insert into solider_in (responsibility, team_number, id) values ('marksman', 388, 920);
insert into solider_in (responsibility, team_number, id) values ('engineer', 389, 486);
insert into solider_in (responsibility, team_number, id) values ('marksman', 390, 747);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 391, 158);
insert into solider_in (responsibility, team_number, id) values ('scout', 392, 758);
insert into solider_in (responsibility, team_number, id) values ('sniper', 393, 971);
insert into solider_in (responsibility, team_number, id) values ('heavy gunner', 394, 1191);
insert into solider_in (responsibility, team_number, id) values ('reconnaissance', 395, 1032);
insert into solider_in (responsibility, team_number, id) values ('marksman', 396, 104);
insert into solider_in (responsibility, team_number, id) values ('engineer', 397, 849);
insert into solider_in (responsibility, team_number, id) values ('communications specialist', 398, 306);
insert into solider_in (responsibility, team_number, id) values ('sharpshooter', 399, 112);
insert into solider_in (responsibility, team_number, id) values ('grenadier', 400, 1035);
